### ISSUE TITLE
undefined method `[]' for #<Set: {#<MIME::Type: application/json>}>

### ISSUE THREAD

**Issue by florianeck** [lingohub/lingohub_ruby#10]
I just wanted to get started with lingohub using the api to upload my files. i installed lingohub via rubygems and when trying to upload the files i got the following error:

```
lingohub resource:up --directory 'config/locales' --project '*****' --all
Enter your Lingohub credentials.
Email: **********
Password  (please leave blank if you want to use your API token): 
API key: *********************************
/Users/user/.rvm/gems/ruby-2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:307:in `type_for_extension': undefined method `[]' for #<Set: {#<MIME::Type: application/json>}> (NoMethodError)
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:312:in `type_for_extension'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:286:in `block (2 levels) in stringify_headers'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:286:in `map'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:286:in `block in stringify_headers'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `each'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `inject'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `stringify_headers'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:92:in `make_headers'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:58:in `initialize'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `new'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/rest-client-1.6.7/lib/restclient/resource.rb:51:in `get'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/lingohub-0.4.1/lib/lingohub/client.rb:82:in `process'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/lingohub-0.4.1/lib/lingohub/client.rb:57:in `get'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/lingohub-0.4.1/lib/lingohub/models/projects.rb:16:in `all'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/lingohub-0.4.1/lib/lingohub/commands/auth.rb:23:in `check'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/lingohub-0.4.1/lib/lingohub/commands/auth.rb:118:in `ask_for_and_save_credentials'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/lingohub-0.4.1/lib/lingohub/commands/auth.rb:47:in `get_credentials'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/lingohub-0.4.1/lib/lingohub/commands/auth.rb:31:in `user'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/lingohub-0.4.1/lib/lingohub/commands/auth.rb:12:in `init_lingohub'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/lingohub-0.4.1/lib/lingohub/commands/auth.rb:8:in `client'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/lingohub-0.4.1/lib/lingohub/command.rb:45:in `run_internal'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/lingohub-0.4.1/lib/lingohub/commands/base.rb:17:in `lingohub'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/lingohub-0.4.1/lib/lingohub/commands/base.rb:107:in `project'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/lingohub-0.4.1/lib/lingohub/commands/resource.rb:26:in `up'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/lingohub-0.4.1/lib/lingohub/command.rb:45:in `run_internal'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/lingohub-0.4.1/lib/lingohub/command.rb:18:in `run'
	from /Users/user/.rvm/gems/ruby-2.2.0/gems/lingohub-0.4.1/bin/lingohub:13:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.2.0/bin/lingohub:22:in `load'
	from /Users/user/.rvm/gems/ruby-2.2.0/bin/lingohub:22:in `<main>'
	from /Users/user/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/user/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by wok** [comment]
Same here with ruby 2.3.4

```
% lingohub project:list
/Users/wok/.rvm/gems/ruby-2.3.4/gems/rest-client-1.6.7/lib/restclient/request.rb:307:in `type_for_extension': undefined method `[]' for #<Set: {#<MIME::Type: application/json>}> (NoMethodError)
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/rest-client-1.6.7/lib/restclient/request.rb:312:in `type_for_extension'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/rest-client-1.6.7/lib/restclient/request.rb:286:in `block (2 levels) in stringify_headers'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/rest-client-1.6.7/lib/restclient/request.rb:286:in `map'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/rest-client-1.6.7/lib/restclient/request.rb:286:in `block in stringify_headers'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `each'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `inject'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/rest-client-1.6.7/lib/restclient/request.rb:272:in `stringify_headers'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/rest-client-1.6.7/lib/restclient/request.rb:92:in `make_headers'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/rest-client-1.6.7/lib/restclient/request.rb:58:in `initialize'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `new'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/rest-client-1.6.7/lib/restclient/resource.rb:51:in `get'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/lingohub-0.4.1/lib/lingohub/client.rb:82:in `process'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/lingohub-0.4.1/lib/lingohub/client.rb:57:in `get'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/lingohub-0.4.1/lib/lingohub/models/projects.rb:16:in `all'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/lingohub-0.4.1/lib/lingohub/commands/project.rb:16:in `list'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/lingohub-0.4.1/lib/lingohub/command.rb:45:in `run_internal'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/lingohub-0.4.1/lib/lingohub/command.rb:18:in `run'
	from /Users/wok/.rvm/gems/ruby-2.3.4/gems/lingohub-0.4.1/bin/lingohub:13:in `<top (required)>'
	from /Users/wok/.rvm/gems/ruby-2.3.4/bin/lingohub:22:in `load'
	from /Users/wok/.rvm/gems/ruby-2.3.4/bin/lingohub:22:in `<main>'
	from /Users/wok/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/wok/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by hemju** [comment]
@florianeck @wok I just released a new version with updated dependencies. This should take care of the problem. Should you still have problems, please let me know.
