### ISSUE TITLE
All commands throw exception most of the time

### ISSUE THREAD

**Issue by djcvijic** [lingohub/lingohub_ruby#9]
I am using gem version 0.4.1.
I use "lingohub login" and "lingohub resource:down --all", and most of the time they fail, and print the same exception.
I estimate that this exception occurs about 75% of the time, here it is after an attempt to run "lingohub login":
```
/usr/lib64/ruby/gems/1.8/gems/json-1.8.2/lib/json/common.rb:155:in `parse': 757: unexpected token at '<?xml version="1.0" encoding="UTF-8"?> (JSON::ParserError)
<projects>
  <links>
    <link>
      <rel>self</rel>
      <href>https://api.lingohub.com/v1/projects</href>
      <type>text/xml</type>
    </link>
  </links>
  <members>
    <member>
      <links>
        <link>
          <rel>self</rel>
          <href>https://api.lingohub.com/v1/example/projects/my-project</href>
          <type>text/xml</type>
        </link>
      </links>
      <title>My Project</title>
    </member>
  </members>
</projects>
'
        from /usr/lib64/ruby/gems/1.8/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
        from /usr/lib64/ruby/gems/1.8/gems/lingohub-0.4.1/lib/lingohub/models/projects.rb:16:in `all'
        from /usr/lib64/ruby/gems/1.8/gems/lingohub-0.4.1/lib/lingohub/commands/auth.rb:23:in `check'
        from /usr/lib64/ruby/gems/1.8/gems/lingohub-0.4.1/lib/lingohub/commands/auth.rb:118:in `ask_for_and_save_credentials'
        from /usr/lib64/ruby/gems/1.8/gems/lingohub-0.4.1/lib/lingohub/commands/auth.rb:27:in `reauthorize'
        from /usr/lib64/ruby/gems/1.8/gems/lingohub-0.4.1/lib/lingohub/command.rb:45:in `send'
        from /usr/lib64/ruby/gems/1.8/gems/lingohub-0.4.1/lib/lingohub/command.rb:45:in `run_internal'
        from /usr/lib64/ruby/gems/1.8/gems/lingohub-0.4.1/lib/lingohub/commands/project.rb:7:in `login'
        from /usr/lib64/ruby/gems/1.8/gems/lingohub-0.4.1/lib/lingohub/command.rb:45:in `send'
        from /usr/lib64/ruby/gems/1.8/gems/lingohub-0.4.1/lib/lingohub/command.rb:45:in `run_internal'
        from /usr/lib64/ruby/gems/1.8/gems/lingohub-0.4.1/lib/lingohub/command.rb:18:in `run'
        from /usr/lib64/ruby/gems/1.8/gems/lingohub-0.4.1/bin/lingohub:13
        from /usr/bin/lingohub:23:in `load'
        from /usr/bin/lingohub:23
```
It seems to me like the server is returning XML instead of JSON, but please investigate this.
If I gather any more info I will leave it here.

**Comment by maerzbow** [comment]
Hi there. And thank you for the bug report.

The problem is that we cannot reproduce this behavior.
.. and with version 0.4.1 you are using the actual one.

I have seen that you are using ruby 1.8. Can you try to switch to a newer ruby version?
(Not quite sure if this could help but this is the only idea that I have at the moment)

**Comment by djcvijic** [comment]
Thank you for responding so quickly! Updating my ruby installation to the newest version seems to have eliminated this exception completely. I would suggest adding a minimum required ruby version to the gemspec file if you wish to guard from this issue occurring in the future.
